name: Build and Release JAR

on:
  push:
    branches:
      - main #Release only from main branch
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21' # Updated to JDK 21

      - name: Build with Maven
        run: mvn clean package

      - name: Get version from pom.xml
        id: get_version
        if: github.ref == 'refs/heads/main' #Release only from main branch
        run: |
          echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: Create GitHub Release
        id: create_release
        if: github.ref == 'refs/heads/main' #Release only from main branch
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }} # Use the version from pom.xml
          release_name: Release ${{ env.VERSION }} # Use the version as the release name
          draft: false
          prerelease: false

      - name: Upload JAR as Release Asset
        id: upload-release-asset
        if: github.ref == 'refs/heads/main' #Release only from main branch
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/packagraph-${{ env.VERSION }}.jar # Include the version in the path
          asset_name: packagraph-${{ env.VERSION }}.jar # Include the version in the asset name
          asset_content_type: application/java-archive
